import React, { useState } from 'react';
import { Card, Typography, Button, Input, Steps, message, Result, Space } from 'antd';
import { QrcodeOutlined, KeyOutlined, CheckCircleOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import api from '../../../lib/api';

const { Title, Text } = Typography;

export const MFASetupPage: React.FC = () => {
  const [current, setCurrent] = useState(0);
  const [qrCodeUrl, setQrCodeUrl] = useState('');
  const [secret, setSecret] = useState('');
  const [token, setToken] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleStartSetup = async () => {
    setLoading(true);
    try {
      // Mocked endpoint for MFA setup initiation
      // const res = await api.post('/auth/mfa/setup');
      // setQrCodeUrl(res.data.qrCode);
      // setSecret(res.data.secret);
      
      // Simulating response
      setTimeout(() => {
        setQrCodeUrl('https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=otpauth://totp/KiroERP:admin?secret=JBSWY3DPEHPK3PXP&issuer=KiroERP');
        setSecret('JBSWY3DPEHPK3PXP');
        setCurrent(1);
        setLoading(false);
      }, 1000);
    } catch (e) {
      message.error('Failed to initiate MFA setup');
      setLoading(false);
    }
  };

  const handleVerify = async () => {
    if (token.length !== 6) return message.warning('Token must be 6 digits');
    
    setLoading(true);
    try {
      // Mocked endpoint for MFA verification
      // await api.post('/auth/mfa/verify', { token });
      
      // Simulating success
      setTimeout(() => {
        message.success('MFA successfully enabled!');
        setCurrent(2);
        setLoading(false);
      }, 1000);
    } catch (e) {
      message.error('Invalid token. Please try again.');
      setLoading(false);
    }
  };

  const steps = [
    {
      title: 'Initiate',
      content: (
        <div style={{ textAlign: 'center', padding: '40px 0' }}>
          <QrcodeOutlined style={{ fontSize: 48, color: '#8B5CF6', marginBottom: 16 }} />
          <Title level={4}>Secure Your Account</Title>
          <Text style={{ display: 'block', marginBottom: 24, color: '#94A3B8' }}>
            Multi-factor authentication adds an extra layer of security to your Kiro ERP account.
          </Text>
          <Button type="primary" size="large" onClick={handleStartSetup} loading={loading}>
            Set up Authenticator App
          </Button>
        </div>
      )
    },
    {
      title: 'Scan QR & Verify',
      content: (
        <div style={{ textAlign: 'center', padding: '20px 0' }}>
          <Text style={{ display: 'block', marginBottom: 16, color: '#E2E8F0' }}>
            1. Open Google Authenticator, Authy, or your preferred TOTP app.
          </Text>
          <img src={qrCodeUrl} alt="QR Code" style={{ borderRadius: 8, padding: 8, background: '#fff', marginBottom: 16 }} />
          <Text style={{ display: 'block', marginBottom: 24, color: '#94A3B8' }}>
            Or enter this code manually: <Text code style={{ fontSize: 16, letterSpacing: 2 }}>{secret}</Text>
          </Text>
          
          <Text style={{ display: 'block', marginBottom: 8, color: '#E2E8F0' }}>
            2. Enter the 6-digit code generated by the app:
          </Text>
          <Space>
            <Input 
              prefix={<KeyOutlined />} 
              placeholder="000000" 
              value={token}
              onChange={e => setToken(e.target.value.replace(/\D/g, '').slice(0, 6))}
              style={{ width: 150, textAlign: 'center', letterSpacing: 4, fontSize: 18 }}
              maxLength={6}
            />
            <Button type="primary" onClick={handleVerify} loading={loading}>Verify & Enable</Button>
          </Space>
        </div>
      )
    },
    {
      title: 'Complete',
      content: (
        <Result
          icon={<CheckCircleOutlined style={{ color: '#10B981' }} />}
          title={<span style={{ color: '#E2E8F0' }}>MFA Enabled Successfully!</span>}
          subTitle={<span style={{ color: '#94A3B8' }}>Your account is now protected with 2-step verification.</span>}
          extra={[
            <Button type="primary" key="console" onClick={() => navigate('/')}>
              Go to Dashboard
            </Button>,
          ]}
        />
      )
    }
  ];

  return (
    <div className="page-container" style={{ maxWidth: 600, margin: '40px auto' }}>
      <Card className="stat-card" style={{ padding: 24 }}>
        <Title level={3} style={{ marginBottom: 32, textAlign: 'center' }}>Multi-Factor Authentication</Title>
        <Steps current={current} items={steps.map(s => ({ title: s.title }))} style={{ marginBottom: 24 }} />
        <div className="steps-content" style={{ minHeight: 300, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          {steps[current].content}
        </div>
      </Card>
    </div>
  );
};
