export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  PERIOD_LOCKED = 'PERIOD_LOCKED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
